### ISSUE TITLE
Not Firing

### ISSUE THREAD

**Issue by BuddyLReno** [yoshuawuyts/chrome-fartscroll#1]
I'm on Chrome 37.  Script doesn't fire.  Not sure why.  Looking through network tab to see if anything is amiss.

**Comment by yoshuawuyts** [comment]
Hey @BuddyLReno, have you tried it on a `https` site? If I recall correctly that's the only place where it works.

**Comment by BuddyLReno** [comment]
@yoshuawuyts Yeah, I loaded up Facebook, Github, Google+ and a few others but I wasn't getting anything.

**Comment by BuddyLReno** [comment]
@yoshuawuyts not sure if i'm supposed to see inject.js in my network tab, unfamiliar with Chrome extensions, but it wasn't there.

**Comment by yoshuawuyts** [comment]
hmh, it should be there I think. Might look into this later today.

**Comment by BuddyLReno** [comment]
@yoshuawuyts Found a fix for this issue.  The chrome api wrapper around the inject.js script was killing it.

**Comment by yoshuawuyts** [comment]
@BuddyLReno Thanks a lot! I've also added you as a contributor, feel free to push in any improvements as you see fit.

I'll have to check out if I can add contributors to the Chrome App store to give you publishing rights.

**Comment by BuddyLReno** [comment]
@yoshuawuyts thanks man!  It was fun to figure out how it all worked :)  If chrome's web store allows for multiple users, I'll definitely update the extension for you.  If not, let me know when you've got that pushed up.  I'll send you an email with my email address since I don't have it publicly listed on my GH profile.

**Comment by yoshuawuyts** [comment]
I think this is resolved. If not feel free to reopen.
